spring:
  application:
    name: order

  datasource:
    url: jdbc:mysql://localhost:3306/order-svc
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
#        use_sql_comments: true
#        generate_statistics: true

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      com.laundry.order: DEBUG

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

